<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="true" />

<title>Sitzung 5: Regressionsanalyse II - Modelloptimierung</title>

<p style="margin-bottom:90px">
  <img src="https://upload.wikimedia.org/wikipedia/de/thumb/f/f0/Goethe-Logo.svg/500px-Goethe-Logo.svg.png" style="position:absolute;top:10px;right:10px;" width="150" height="81.6" />
</p>

<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-modelloptimierung" class="section level2">
<h2>Modelloptimierung</h2>
<p>Bei der Regressionsanalyse hat die Modelloptimierung zum Ziel, ein Regresionsmodell zu verbessern, das heißt, möglichst viel Varianz der abhängigen Variable zu erklären. <strong>Modelloptimierung</strong> bedeutet, ein Modell zu verbessern, durch:</p>
<ul>
<li>Aufnehmen zusätzlicher, bedeutsamer Prädiktoren</li>
<li>Ausschließen von Prädiktoren, die nicht zur Varianzaufklärung beitragen</li>
</ul>
<p><strong>Ziel:</strong></p>
<ul>
<li>sparsames Modell, in dem jeder enthaltene Prädiktor einen Beitrag zur Varianzaufklärung des Kriteriums leistet</li>
<li>kein wichtiger Prädiktor vergessen</li>
</ul>
<p>Dafür kann man beispielsweise das Inkrement, also den Zuwachs an erklärter Kriteriumsvarianz durch Hinzunahme eines Prädiktors, sowie das Dekrement, also die Verringerung an erklärter Varianz durch Ausschluss eines Prädiktors betrachten.</p>
<p><strong>Methoden:</strong></p>
<ul>
<li>Forward-Selection: Hinzunahme des Prädiktors mit dem größten, signifikanten Inkrement (bis keine zusätzliche Varianzaufklärung durch weitere Hinzunahme erreicht werden kann)</li>
<li>Backward-Selection: Ausschluss von Prädiktoren mit dem kleinsten Dekrement, ohne die erklärte Kriteriumsvarianz signifikant zu reduzieren</li>
<li>Stepwise Regression: Wie bei der Forward-Selection wird immer der Prädiktor mit dem größten Inkrement hinzugenommen, und zusätzlich in jedem Schritt geprüft, ob ein anderer Prädiktor wieder gelöscht werden kann (nicht-signifikantes Dekrement). <strong>Problematisch, wird nicht empfohlen</strong></li>
</ul>
</div>
<div id="section-übungs-datensatz" class="section level2">
<h2>Übungs-Datensatz</h2>
<p>Die Modelloptimierung wird am gleichen Datensatz demonstriert, der auch in der Sitzung zu Regression I verwendet wurde. Eine Stichprobe von 100 Schülerinnen und Schülern hat einen Lese- und einen Mathematiktest bearbeitet, und zusätzlich dazu einen allgemeinen Intelligenztest absolviert. Im Datensatz enthalten ist zudem das Geschlecht (Variable: <code>female</code>, 0 = m, 1 = w). Die abhängige Variable ist die Matheleistung, die durch die anderen Variablen im Datensatz vorhergesagt werden soll.</p>
<p>Über das Paket PsyBSc7 laden Sie den Datensatz wie gehabt wie folgt:</p>
<pre class="r"><code># Datensatz laden
data(Schulleistungen, package = &quot;PsyBSc7&quot;)</code></pre>
<p>Der Vollständigkeit halber und zur Erinnerung: Wenn Sie mit einem Datensatz arbeiten wollen, der lokal auf ihrem Rechner gespeichert ist, könnten sie diesen wie folgt laden:</p>
<pre class="r"><code># Datensatz laden
Schulleistungen &lt;- readRDS(&quot;Schulleistungen.rda&quot;)</code></pre>
</div>
<div id="section-inkrement-und-dekrement" class="section level2">
<h2>Inkrement und Dekrement</h2>
<div id="section-testen-eines-inkrements" class="section level3">
<h3>Testen eines Inkrements</h3>
<p>Vergleich eines eingeschränkten Modells <span class="math inline">\(M_c\)</span> mit weniger Prädiktoren gegen ein uneingeschränktes Modell <span class="math inline">\(M_u\)</span> mit zusätzlichen Prädiktoren. Beispiel: Inkrement durch Hinzunahme von Intelligenz. Führt die Hinzunahme von Intelligenz zu einem signifikanten Zuwachs an erklärter Varianz, wenn Lesekompetenz und Geschlecht bereits im Vorhersagemodell sind?</p>
<pre class="r"><code>m.c &lt;- lm(math ~ reading + female, data = Schulleistungen)      # constrained
m.u &lt;- lm(math ~ reading + female + IQ, data = Schulleistungen) # unconstrained
summary(m.c)</code></pre>
<pre><code>## 
## Call:
## lm(formula = math ~ reading + female, data = Schulleistungen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -204.12  -64.84   -7.69   45.14  490.01 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 369.9663    51.1049   7.239 1.07e-10 ***
## reading       0.4431     0.1011   4.381 2.99e-05 ***
## female      -52.3994    21.4960  -2.438   0.0166 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 106.2 on 97 degrees of freedom
## Multiple R-squared:  0.1897, Adjusted R-squared:  0.173 
## F-statistic: 11.36 on 2 and 97 DF,  p-value: 3.701e-05</code></pre>
<pre class="r"><code>summary(m.u)</code></pre>
<pre><code>## 
## Call:
## lm(formula = math ~ reading + female + IQ, data = Schulleistungen)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -96.46 -50.69 -20.66  18.53 455.03 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  75.416510  55.602607   1.356    0.178    
## reading      -0.002986   0.098679  -0.030    0.976    
## female      -26.310648  17.318600  -1.519    0.132    
## IQ            5.112758   0.663512   7.706 1.19e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 83.91 on 96 degrees of freedom
## Multiple R-squared:  0.4994, Adjusted R-squared:  0.4837 
## F-statistic: 31.92 on 3 and 96 DF,  p-value: 2.121e-14</code></pre>
<ul>
<li>Determinationskoeffizient ohne IQ (“constrained”): <span class="math inline">\(R_c^2=0.19\)</span></li>
<li>Determinationskoeffizient mit IQ (“unconstrained”): <span class="math inline">\(R_u^2=0.50\)</span></li>
</ul>
<p>Die Differenz aus beiden Determinationskoeffizienten können wir wie folgt berechnen:</p>
<pre class="r"><code># Inkrement = Differenz in R2 aus restringiertem Modell 2 minus R2 aus unrestringiertem Modell 1
summary(m.u)$r.squared - summary(m.c)$r.squared</code></pre>
<pre><code>## [1] 0.3096366</code></pre>
<p>Wir sehen also, dass das Modell mit IQ mehr Varianz erklärt als das ohne IQ. Die Hinzunahme des IQ führt zu einem Zuwachs von 31% erklärter Varianz (<span class="math inline">\(\Delta R^2=0.31\)</span>). Dieses <em>Inkrement</em> soll auf Signifikanz getestet werden. Der Modellvergleich kann mit der <code>anova</code>-Funktion vorgenommen werden. Ergänzen Sie den Befehl, um die beiden zuvor erstellten Modelle zu vergleichen.</p>
<div class="tutorial-exercise" data-label="anova" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Modellvergleich mit der anova-Funktion
anova(...)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Das Inkrement des IQs ist auf einem Alpha-Fehlerniveau von 0.05 signifikant von null verschieden (<span class="math inline">\(p=0.000\)</span>).</p>
<p>Zum Vergleich finden Sie hier die Berechnung des F-Tests nach Vorlesungs-Folie 11 aus der zweiten Vorlesung zu Regression:</p>
<pre class="r"><code>R2.u &lt;- summary(m.u)$r.squared
R2.c &lt;- summary(m.c)$r.squared
df.diff &lt;- summary(m.u)$df[1] - summary(m.c)$df[1]
df.u &lt;- summary(m.u)$df[2]
F.diff &lt;- ((R2.u - R2.c) / df.diff) /
  ((1 - R2.u) / df.u)
p.diff &lt;- 1-pf(F.diff, df.diff, df.u)
F.diff</code></pre>
<pre><code>## [1] 59.37622</code></pre>
<pre class="r"><code>p.diff</code></pre>
<pre><code>## [1] 1.186384e-11</code></pre>
</div>
<div id="section-testen-eines-dekrements" class="section level3">
<h3>Testen eines Dekrements</h3>
<p>Das Dekrement ist der Unterschied im <span class="math inline">\(R^2\)</span> zwischen dem restringierten Modell <span class="math inline">\(M_c\)</span> und dem unrestringierten Modell <span class="math inline">\(M_u\)</span>. Die Testung eines Dekrements erfolgt analog dem Inkrement: das eingeschränkte Modell <span class="math inline">\(M_c\)</span> mit weniger Prädiktoren wird mit dem uneingeschränkten Modell <span class="math inline">\(M_u\)</span> mit mehr Prädiktoren verglichen. Es soll nun geprüft werden, ob das <em>Weglassen</em> des Geschlechts aus dem Modell zu einem signifikanten Rückgang der erklärten Varianz führt. Stellen Sie nach dem Modell von oben das uneingeschränkte und das eingeschränkte Modell auf, berechnen Sie die Differenz in der Varianzaufklärung und testen Sie, ob dieser Unterschied signifikant ist.</p>
<div class="tutorial-exercise" data-label="compare" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>m.u &lt;- lm(math ~ ..., data = Schulleistungen) # unconstrained
m.c &lt;- lm(math ~ ..., data = Schulleistungen) # constrained

summary(m.u)$r.squared - summary(m.c)$r.squared
# Modellvergleich mit der anova-Funktion
anova(m.c, m.u)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Der Ausschluss des Geschlechts führt zu einer Verringerung von 31% erklärter Varianz (<span class="math inline">\(\Delta R^2=0.31\)</span>). Dieser Unterschied ist <em>nicht</em> signifikant von null verschieden (<span class="math inline">\(p=0.000\)</span>)</p>
</div>
</div>
<div id="section-schrittweise-selektion-von-prädiktoren" class="section level2">
<h2>Schrittweise Selektion von Prädiktoren</h2>
<p>Eine “theoriefreie” schrittweise Auswahl von Prädiktoren kann in R mit der <code>step</code>-Funktion erfolgen. Diese macht, anders als unser zuvor demonstriertes Vorgehen, nicht von Partialkorrelationen und Inkrementen Gebrauch, sondern vom sogenannten Informationskriterium AIC (<em>Akaike Information Criterion</em>). Dieses basiert auf der Likelihood eines geschätzten Modells <span class="math inline">\(L(\hat{\theta})\)</span> und der Anzahl der Modellparametern <span class="math inline">\(p\)</span>:</p>
<p><span class="math inline">\(AIC=-2L(\hat{\theta}) + 2p\)</span></p>
<p>Die Likelihood bezeichnet ein Maß für die Plausibilität/Wahrscheinlichkeit eines Modells, unter Berücksichtigung der gegebenen (empirisch erhobenen) Daten. Anders ausgedrückt: Die Likelihood eines Modells, gegeben die empirischen Daten. Um das beste Modell zu finden, kann man die Likelihood verschiedener Modelle vergleichen.</p>
<p>Für lineare Regressionsmodelle lässt sich der AIC wie folgt darstellen:</p>
<p><span class="math inline">\(AIC_{\sigma}=n \cdot log(\sigma_e^2) + 2p\)</span></p>
<p>Der AIC ist hier eine Funktion der Stichprobengröße <span class="math inline">\(n\)</span>, der Residualvarianz <span class="math inline">\(\sigma_e^2\)</span> und der Anzahl der Parameter (= Regressionskoeffizienten) <span class="math inline">\(p=m+1\)</span>. Es wird hier ersichtlich, dass der AIC von der Varianz der abhängigen Variablen abhängt, da diese wiederum die Residualvarianz beeinflusst.</p>
<p>Der AIC ist ein sogenanntes inverses Maß, das bedeutet, dass Modelle mit einem kleineren AIC besser sind als Modelle mit einem größeren AIC. Der AIC wird durch den Term <span class="math inline">\(n \cdot log(\sigma_e^2)\)</span> kleiner, wenn die Residualvarianz kleiner wird, also mehr Varianz erklärt wird. Durch den “Strafterm” <span class="math inline">\(2p\)</span> wird der AIC größer, wenn das Modell mehr Prädiktoren enthält. Es soll also ein Modell gefunden werden, das mit möglichst wenigen Prädiktoren möglichst viel Varianz erklärt (<em>Sparsamkeitsprinzip</em>).</p>
<p>Die Schrittweise Selektion kann “vorwärts”, “rückwärts”, oder in beide Richtungen erfolgen. Die Standardeinstellung der <code>step</code>-Funktion ist die, dass ein Modell mit allen möglichen Prädiktoren als Ausgangspunkt genommen wird. Es wird dann der Prädiktor ausgeschlossen, der die größte Reduktion des AIC erlaubt, dann der nächste usw. In jedem Schritt wird auch wieder geprüft, ob Prädiktoren, die <em>nicht</em> im Modell sind, bei Aufnahme wieder zu einer Reduktion des AIC führen würden. Das Verfahren stoppt, wenn:</p>
<ol style="list-style-type: decimal">
<li>nur noch Prädiktoren im Modell sind, deren Ausschluss zu einer Erhöhung des AIC führen würden und</li>
<li>nur Prädiktoren “übrig” sind, deren Einschluss den AIC nicht verbessern würde.</li>
</ol>
<p>Einfaches Beispiel: Optimierung des Modells für Mathematikleistung, Start mit allen drei möglichen Prädiktoren:</p>
<pre class="r"><code># Modell mit allen Prädiktoren
m &lt;- lm(math ~ reading + female + IQ, data = Schulleistungen)
# Optimierung
summary(step(m))</code></pre>
<pre><code>## Start:  AIC=889.88
## math ~ reading + female + IQ
## 
##           Df Sum of Sq     RSS    AIC
## - reading  1         6  675993 887.88
## &lt;none&gt;                  675987 889.88
## - female   1     16252  692239 890.25
## - IQ       1    418099 1094086 936.03
## 
## Step:  AIC=887.88
## math ~ female + IQ
## 
##          Df Sum of Sq     RSS    AIC
## &lt;none&gt;                 675993 887.88
## - female  1     17222  693215 888.39
## - IQ      1    634538 1310531 952.08</code></pre>
<pre><code>## 
## Call:
## lm(formula = math ~ female + IQ, data = Schulleistungen)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -96.60 -50.72 -20.91  18.41 455.09 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  75.1532    54.6335   1.376    0.172    
## female      -26.4255    16.8102  -1.572    0.119    
## IQ            5.1010     0.5346   9.542 1.31e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 83.48 on 97 degrees of freedom
## Multiple R-squared:  0.4994, Adjusted R-squared:  0.489 
## F-statistic: 48.38 on 2 and 97 DF,  p-value: 2.67e-15</code></pre>
<p>Es ist zu sehen dass es im Ausgangsmodell nur eine Möglichkeit gibt, das Modell zu verbessern, nämlich den Ausschluss von Lesekompetenz (<code>reading</code>) (AIC von 889.88 auf 887.88). Danach gibt es keine Möglichkeit zur Verbesserung mehr, beide verbleibenden Prädiktoren würden bei einem Ausschluss zu einer Verschlechterung des AIC führen (<code>female</code> auf 888.25 und <code>IQ</code> auf 952.08). Damit sind Geschlecht und IQ die Prädiktoren für das optimierte Modell.</p>
<p>An der Ausgabe für das “finale” Modell am Schluss ist zu sehen, dass der Effekt von Geschlecht im finalen Modell hier <em>nicht</em> signifikant ist. Auch oben haben wir gesehen, dass unter Betrachtung des Dekrements dieser Prädiktor wegfallen würde.</p>
<p>Sparsamkeit wird beim AIC im “Strafterm” <span class="math inline">\(2p\)</span> nicht so hoch gewichtet wie bei anderen Informationskriterien. In der Funktion <code>step</code> kann man über die Veränderung des Parameters <code>k</code> steuern, wie streng die Prädiktorauswahl vorgenommen wird. Wenn man hier <span class="math inline">\(k = log(n)\)</span> angibt, wird statt des AIC das sogenannte Bayessche Informationskriterium BIC (<em>Bayesian Information Criterion</em>) verwendet.</p>
<p><span class="math inline">\(BIC=-2L(\hat{\theta}) + log(n)\cdot p\)</span></p>
<p>Vorsicht, in der Ausgabe der <code>step</code>-Funktion steht immer AIC, auch wenn dies nur mit der Standardeinstellung von <span class="math inline">\(k=2\)</span> tatsächlich dem AIC entspricht!</p>
<pre class="r"><code># Optimierung mit BIC
summary(step(m, k=log(nrow(Schulleistungen))))</code></pre>
<pre><code>## Start:  AIC=900.3
## math ~ reading + female + IQ
## 
##           Df Sum of Sq     RSS    AIC
## - reading  1         6  675993 895.69
## - female   1     16252  692239 898.07
## &lt;none&gt;                  675987 900.30
## - IQ       1    418099 1094086 943.84
## 
## Step:  AIC=895.69
## math ~ female + IQ
## 
##          Df Sum of Sq     RSS    AIC
## - female  1     17222  693215 893.60
## &lt;none&gt;                 675993 895.69
## - IQ      1    634538 1310531 957.29
## 
## Step:  AIC=893.6
## math ~ IQ
## 
##        Df Sum of Sq     RSS    AIC
## &lt;none&gt;               693215 893.60
## - IQ    1    657076 1350290 955.67</code></pre>
<pre><code>## 
## Call:
## lm(formula = math ~ IQ, data = Schulleistungen)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -84.14 -51.06 -18.69  24.02 468.71 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  53.9006    53.3302   1.011    0.315    
## IQ            5.1721     0.5366   9.638 7.39e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 84.1 on 98 degrees of freedom
## Multiple R-squared:  0.4866, Adjusted R-squared:  0.4814 
## F-statistic: 92.89 on 1 and 98 DF,  p-value: 7.392e-16</code></pre>
<p>Bei der Verwendung des stengeren Kriteriums wird auch Geschlecht aus dem Modell entfernt, es verbleibt nur der IQ im finalen Modell.</p>
<div id="section-weitere-möglichkeiten" class="section level3">
<h3>Weitere Möglichkeiten</h3>
<p>Wie immer gibt es in R viele weitere Wege, zum selben Ziel zu kommen. Eine Vielzahl von Funktionen für die schrittweise Regression bietet z.B. das Paket <code>olsrr</code>, Im Rahmen des Praktikums verwenden wir soweit möglich die Basis-Funktionen von R und beschränken uns daher bei den Aufgaben für schrittweise Analysen auf die <code>step</code>-Funktion.</p>
<p>Das Paket <code>olsrr</code> beinhaltet verschiedene Funktionen, die für die Regressionsanalyse nützlich sind, u.a. auch Funktionen, die die schrittweise Auswahl von Prädiktoren auf Basis verschiedener Kriterien und nach verschiedenen Methoden (vorwärts, rückwärts, etc.) ermöglichen. Finden Sie <a href="https://olsrr.rsquaredacademy.com/articles/variable_selection.html#best-subset-regression">hier</a> mehr Informationen dazu. Die Funktion <code>ols_step_both_p</code> beinhaltet die Auswahl auf Basis der Signifikanz des Inkrements oder Dekrements und führt in jedem Schritt Tests für Einschluss und Ausschluss durch.<br />
Der Input ist ein Regressionsmodell, das mit der bekannten Funktion <code>lm</code> erstellt wurde. Über die zusätzlichen Argumente kann gesteuert werden, wie streng bei Aufnahme und Ausschluss getestet wird. Über das Argument <code>details</code> können Sie den gesamten Verlauf der schrittweisen Selektion (nicht nur das finale Ergebnis) anzeigen lassen.</p>
<pre class="r"><code># install.packages(&quot;olsrr&quot;)
library(olsrr)</code></pre>
<pre><code>## 
## Attaching package: &#39;olsrr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:datasets&#39;:
## 
##     rivers</code></pre>
<pre class="r"><code># pent = p enter, p-Wert zur Aufnahme ins Modell
# prem = p remove, p-Wert zum Ausschluss aus dem Modell
ols_step_both_p(m, pent = .05, prem = .10, details = TRUE)</code></pre>
<pre><code>## Stepwise Selection Method   
## ---------------------------
## 
## Candidate Terms: 
## 
## 1. reading 
## 2. female 
## 3. IQ 
## 
## We are selecting variables based on p value...
## 
## 
## Stepwise Selection: Step 1 
## 
## - IQ added 
## 
##                          Model Summary                           
## ----------------------------------------------------------------
## R                       0.698       RMSE                 84.105 
## R-Squared               0.487       Coef. Var            14.980 
## Adj. R-Squared          0.481       MSE                7073.620 
## Pred R-Squared          0.468       MAE                  52.958 
## ----------------------------------------------------------------
##  RMSE: Root Mean Square Error 
##  MSE: Mean Square Error 
##  MAE: Mean Absolute Error 
## 
##                                  ANOVA                                  
## -----------------------------------------------------------------------
##                    Sum of                                              
##                   Squares        DF    Mean Square      F         Sig. 
## -----------------------------------------------------------------------
## Regression     657075.570         1     657075.570    92.891    0.0000 
## Residual       693214.751        98       7073.620                     
## Total         1350290.321        99                                    
## -----------------------------------------------------------------------
## 
##                                    Parameter Estimates                                    
## -----------------------------------------------------------------------------------------
##       model      Beta    Std. Error    Std. Beta      t       Sig       lower      upper 
## -----------------------------------------------------------------------------------------
## (Intercept)    53.901        53.330                 1.011    0.315    -51.931    159.733 
##          IQ     5.172         0.537        0.698    9.638    0.000      4.107      6.237 
## -----------------------------------------------------------------------------------------
## 
## 
## 
## No more variables to be added/removed.
## 
## 
## Final Model Output 
## ------------------
## 
##                          Model Summary                           
## ----------------------------------------------------------------
## R                       0.698       RMSE                 84.105 
## R-Squared               0.487       Coef. Var            14.980 
## Adj. R-Squared          0.481       MSE                7073.620 
## Pred R-Squared          0.468       MAE                  52.958 
## ----------------------------------------------------------------
##  RMSE: Root Mean Square Error 
##  MSE: Mean Square Error 
##  MAE: Mean Absolute Error 
## 
##                                  ANOVA                                  
## -----------------------------------------------------------------------
##                    Sum of                                              
##                   Squares        DF    Mean Square      F         Sig. 
## -----------------------------------------------------------------------
## Regression     657075.570         1     657075.570    92.891    0.0000 
## Residual       693214.751        98       7073.620                     
## Total         1350290.321        99                                    
## -----------------------------------------------------------------------
## 
##                                    Parameter Estimates                                    
## -----------------------------------------------------------------------------------------
##       model      Beta    Std. Error    Std. Beta      t       Sig       lower      upper 
## -----------------------------------------------------------------------------------------
## (Intercept)    53.901        53.330                 1.011    0.315    -51.931    159.733 
##          IQ     5.172         0.537        0.698    9.638    0.000      4.107      6.237 
## -----------------------------------------------------------------------------------------</code></pre>
<pre><code>## 
##                               Stepwise Selection Summary                               
## --------------------------------------------------------------------------------------
##                      Added/                   Adj.                                        
## Step    Variable    Removed     R-Square    R-Square     C(p)        AIC        RMSE      
## --------------------------------------------------------------------------------------
##    1       IQ       addition       0.487       0.481    2.4470    1174.1802    84.1048    
## --------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div id="section-aufgaben-zur-eigenständigen-bearbeitung" class="section level2">
<h2>Aufgaben zur eigenständigen Bearbeitung</h2>
<div id="section-datensatz" class="section level3">
<h3>1. Datensatz</h3>
<p>Der Beispieldatensatz enthält Daten zu Lesekompetenz aus der deutschen Stichprobe der PISA-Erhebung in Deutschland 2009. Gegenüber dem letzten Termin sind in dieser Version noch mehr Variablen enthalten, insbesondere über die Eltern und Besitztümer im Elternhaus.</p>
<p>Im Einzelnen enthält der Datensatz die folgenden Variablen:</p>
<ul>
<li>Klassenstufe (<code>Grade</code>)</li>
<li>Alter in Jahren (<code>Age</code>)</li>
<li>Geschlecht (<code>Female</code>, 0=m / 1=w)</li>
<li>Lesekompetenz (<code>Reading</code>)</li>
<li>Lesefreude (<code>JoyRead</code>)</li>
<li>Lernzeit in Minuten für Deutsch (<code>LearnMins</code>)</li>
<li>Sozialstatus (<code>HISEI</code>, “highest international socio-economic index of occupational status”)</li>
<li>Fragebogen-Score für kulturelle Besitztümer zu Hause (<code>CultPoss</code>, z. B. klassische Literatur, Kunstwerke)</li>
<li>Anzahl Bücher zu Hause (<code>Books</code>, eigentlich eine ordinale Ratingskala)</li>
<li>Anzahl Fernseher zu Hause (<code>TVs</code>)</li>
<li>Anzahl Computer zu Hause (<code>Computers</code>)</li>
<li>Anzahl Autos zu Hause (<code>Cars</code>)</li>
<li>Migrationshintergrund (<code>MigHintergrund</code>, 0=beide Eltern in D geboren, 1=min. 1 Elternteil im Ausland geboren)</li>
<li>Bildungsabschluss des Vaters (<code>FatherEdu</code>, International Standard Classification of Education)</li>
<li>Bildungsabschluss der Mutter (<code>MotherEdu</code>, International Standard Classification of Education)</li>
</ul>
<p>Laden Sie den Datensatz und verschaffen Sie sich einen Eindruck über die Daten. Installieren Sie außerdem das Paket “lm.beta”.</p>
</div>
<div id="section-modellkonstruktion-mit-individuellen-merkmalen-der-schülerinnen" class="section level3">
<h3>2. Modellkonstruktion mit individuellen Merkmalen der Schüler/innen</h3>
<p>Untersucht werden sollen verschiedene Modelle zur Vorhersage der Lesekompetenz anhand der individuellen Schülermerkmale Alter, Klassenstufe, Geschlecht und Migrationshintergrund.</p>
<div id="section-a-alter-und-klassenstufe" class="section level4">
<h4>2 a) Alter und Klassenstufe</h4>
<p>Berechnen Sie drei separate Regressionsmodelle mit (1) Alter, (2) Klassenstufe und (3) Alter und Klassenstufe als Prädiktoren für Lesekompetenz. Berechnen Sie die Unterschiede in der erklärten Varianz und deren Signifikanz für die Vergleiche der Modelle 1 vs. 3 und 2 vs. 3. Interpretieren Sie die Ergebnisse. Für welches Modell würden Sie sich entscheiden? Bitte begründen Sie Ihre Antwort. Beziehen Sie sich dabei auf alles, was Sie in beiden bisherigen Sitzungen zur Regression gelernt haben.</p>
</div>
<div id="section-b-hinzunahme-von-geschlecht-in-migrationshintergrund" class="section level4">
<h4>2 b) Hinzunahme von Geschlecht in Migrationshintergrund</h4>
<p>Ergänzen Sie Modell 3 (mit Alter und Klassenstufe) um die beiden Prädiktoren Geschlecht und Migrationshintergrund. Wie viel zusätzliche Varianz erklären diese beiden Prädiktoren? Interpretieren Sie auch hier die Ergebnisse und begründen, für welches Modell Sie sich entscheiden würden.</p>
</div>
</div>
<div id="section-schrittweise-analyse-mit-eigenschaften-des-elternhauses" class="section level3">
<h3>3. Schrittweise Analyse mit Eigenschaften des Elternhauses</h3>
<p>Es soll untersucht werden, welche Charakteristika der Eltern und Besitztümer des Elternhauses die besten Prädiktoren für die Lesekompetenz der getesteten Schüler/innen sind. Aus den folgenden Variablen soll ein optimales Vorhersagemodell gebildet werden:</p>
<ul>
<li>Sozialstatus (<code>HISEI</code>)</li>
<li>Bildungsabschluss des Vaters (<code>FatherEdu</code>)</li>
<li>Bildungsabschluss der Mutter (<code>MotherEdu</code>)</li>
<li>Kulturelle Besitztümer (<code>CultPoss</code>)</li>
<li>Anzahl Bücher zu Hause (<code>Books</code>)</li>
<li>Anzahl Fernseher zu Hause (<code>TVs</code>)</li>
<li>Anzahl Computer zu Hause (<code>Computers</code>)</li>
<li>Anzahl Autos zu Hause (<code>Cars</code>)</li>
</ul>
<div id="section-a-führen-sie-eine-schrittweise-regressionsanalyse-mit-dem-aic-als-auswahlkriterium-durch." class="section level4">
<h4>3 a) Führen Sie eine schrittweise Regressionsanalyse mit dem AIC als Auswahlkriterium durch.</h4>
<p>Geben Sie zunächst an, welche Prädiktoren im Modell mit allen Prädiktoren signifikant sind. Führen Sie dann eine schrittweise Regressionsanalyse durch. Welche Prädiktoren werden hier ausgewählt?</p>
</div>
<div id="section-b-ermitteln-sie-auch-standardiserte-regressionsgewichte-für-das-finale-modell.-wie-stark-sind-die-effekte-der-ausgewählten-prädiktoren-im-vergleich" class="section level4">
<h4>3 b) Ermitteln Sie auch standardiserte Regressionsgewichte für das finale Modell. Wie stark sind die Effekte der ausgewählten Prädiktoren im Vergleich?</h4>
</div>
<div id="section-c-führen-sie-zum-vergleich-die-schrittweise-regressionsanalyse-nun-auf-basis-von-inkrement-und-dekrement-mit-dem-package-olsrr-durch-und-vergleichen-sie-den-output-mit-der-lösung-aus-aufgabe-3a." class="section level4">
<h4>3 c) Führen Sie zum Vergleich die schrittweise Regressionsanalyse nun auf Basis von Inkrement und Dekrement (mit dem Package <code>olsrr</code>) durch und vergleichen Sie den Output mit der Lösung aus Aufgabe 3a).</h4>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
library(fontawesome)
#source('setup.R')
library(psych)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-anova-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-anova-code-editor`)), session)
output$`tutorial-exercise-anova-output` <- renderUI({
  `tutorial-exercise-anova-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-compare-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-compare-code-editor`)), session)
output$`tutorial-exercise-compare-output` <- renderUI({
  `tutorial-exercise-compare-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jqueryui"]},{"type":"character","attributes":{},"value":["1.11.4"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jqueryui"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-ui.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tocify"]},{"type":"character","attributes":{},"value":["1.9.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/tocify"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.tocify.js"]},{"type":"character","attributes":{},"value":["jquery.tocify.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78]}},"value":[{"type":"character","attributes":{},"value":["abind","assertthat","backports","base","car","carData","cellranger","colorspace","compiler","crayon","curl","data.table","datasets","digest","dplyr","ellipsis","evaluate","fastmap","fontawesome","forcats","foreign","ggplot2","glue","goftest","graphics","grDevices","grid","gridExtra","gtable","haven","hms","htmltools","htmlwidgets","httpuv","jsonlite","knitr","later","lattice","learnr","lifecycle","magrittr","markdown","methods","mime","mnormt","munsell","nlme","nortest","olsrr","openxlsx","parallel","pillar","pkgconfig","promises","psych","purrr","R6","Rcpp","readxl","rio","rlang","rmarkdown","rprojroot","scales","shiny","stats","stringi","stringr","tibble","tidyselect","tools","utils","vctrs","withr","xfun","xtable","yaml","zip"]},{"type":"character","attributes":{},"value":["1.4-5","0.2.1","1.1.7","4.0.0","3.0-7","3.0-3","1.1.0","1.4-1","4.0.0","1.3.4","4.3","1.12.8","4.0.0","0.6.25","0.8.5","0.3.1","0.14","1.0.1","0.1.0","0.5.0","0.8-76","3.3.0","1.4.1","1.2-2","4.0.0","4.0.0","4.0.0","2.3","0.3.0","2.2.0","0.5.3","0.4.0","1.5.1","1.5.2","1.6.1","1.28","1.0.0","0.20-41","0.10.1","0.2.0","1.5","1.1","4.0.0","0.9","1.5-7","0.5.0","3.1-147","1.0-4","0.5.3","4.1.5","4.0.0","1.4.4","2.0.3","1.1.0","1.9.12.31","0.3.4","2.4.1","1.0.4.6","1.3.1","0.5.16","0.4.6","2.1","1.3-2","1.1.1","1.4.0.2","4.0.0","1.4.6","1.4.0","3.0.1","1.1.0","4.0.0","4.0.0","0.3.0","2.2.0","0.13","1.8-4","2.2.1","2.0.4"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Sitzung 5: Regressionsanalyse II - Modelloptimierung</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->


<hr />
<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<p style="text-align: center;">Johanna Schüller</p>
<p style="text-align: center;">(Unterlagen basieren auf Material von Martin Schultze)</p>
<p style="text-align: center;">PsyBSc7 Praktikum, SoSe 2020</p>
<p style="text-align: center;">
    <a title="OLAT" href="https://olat-ce.server.uni-frankfurt.de/olat/auth/RepositoryEntry/8149106692" class="fa fa-external-link"></a>
    <a title="GitHub" href="https://github.com/martscht/PsyBSc7" class="fa fa-github"></a>
    <a title="Lizenz" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" class="fab fa-creative-commons"></a>
</p>


<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
